### ISSUE TITLE
Battery issue

### ISSUE THREAD

**Issue by tuandunguit** [m3rtngs/HP-Pavilion-CE-1005NA-Hackintosh-OpenCore-EFI#1]
Thank you very much for your EFI, it works for me - HP Pavilion 14-ce2039TU, except battery and sound (sometime work, sometime not). Did you able to get it work? Appreciate for any suggestion.

**Comment by m3rtngs** [comment]
My battery and sound both work, what version of macOS are you using?

**Comment by tuandunguit** [comment]
Catalina 10.15.7, is it difference with yours?

**Comment by m3rtngs** [comment]
I recently used it on Big Sur and Catalina and had no issues. You need to check the ALCID that you should be using then change it via the config to the correct one.

**Comment by tuandunguit** [comment]
Yeah, i used alcid=28, it seems work consistently now.
Trying to fix battery status, did you apply any dsdt patch? I tried Rehabman patch for HP Pavilion n012tx, but it get compile error.

**Comment by m3rtngs** [comment]
I made my own patch for my own laptop, it may not work with yours.

**Comment by tuandunguit** [comment]
Understood, at least our laptops quite the same, and most of the things work on my laptop too.
Only battery need to fix, trying on this :)
Thank you so much for your sharing!

**Comment by m3rtngs** [comment]
You're welcome.
